"""
This type stub file was generated by pyright.
"""

import os
from __future__ import absolute_import, division, print_function, unicode_literals

__file__ = os.path.abspath(__file__)
adapter_host = None
channel = None
def connect(host, port):
    ...

