"""
This type stub file was generated by pyright.
"""

from kombu.serialization import disable_insecure_serializers as _disable_insecure_serializers, registry
from celery.exceptions import ImproperlyConfigured
from .serialization import register_auth

"""Message Signing Serializer."""
CRYPTOGRAPHY_NOT_INSTALLED = """\
You need to install the cryptography library to use the auth serializer.
Please install by:

    $ pip install cryptography
"""
SECURITY_SETTING_MISSING = """\
Sorry, but you have to configure the
    * security_key
    * security_certificate, and the
    * security_cert_store
configuration settings to use the auth serializer.

Please see the configuration reference for more information.
"""
SETTING_MISSING = """\
You have to configure a special task serializer
for signing and verifying tasks:
    * task_serializer = 'auth'

You have to accept only tasks which are serialized with 'auth'.
There is no point in signing messages if they are not verified.
    * accept_content = ['auth']
"""
def setup_security(allowed_serializers=..., key=..., cert=..., store=..., digest=..., serializer=..., app=...):
    """See :meth:`@Celery.setup_security`."""
    ...

def disable_untrusted_serializers(whitelist=...):
    ...

