"""
This type stub file was generated by pyright.
"""

"""Secure serializer."""
class SecureSerializer:
    """Signed serializer."""
    def __init__(self, key=..., cert=..., cert_store=..., digest=..., serializer=...) -> None:
        ...
    
    def serialize(self, data):
        """Serialize data structure into string."""
        ...
    
    def deserialize(self, data):
        """Deserialize data structure from string."""
        ...
    


def register_auth(key=..., cert=..., store=..., digest=..., serializer=...):
    """Register security serializer."""
    ...

