"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager

"""Utilities used by the message signing serializer."""
def get_digest_algorithm(digest=...):
    """Convert string to hash object of cryptography library."""
    ...

@contextmanager
def reraise_errors(msg=..., errors=...):
    """Context reraising crypto errors as :exc:`SecurityError`."""
    ...

