"""
This type stub file was generated by pyright.
"""

import os
from multiprocessing.context import assert_spawning

"""Helper module to factorize the conditional multiprocessing import logic

We use a distinct module to simplify import statements and avoid introducing
circular dependencies (for instance for the assert_spawning name).
"""
mp = int(os.environ.get('JOBLIB_MULTIPROCESSING', 1)) or None
if mp:
    ...
if mp is not None:
    ...
if mp is not None:
    ...
else:
    assert_spawning = None
