"""
This type stub file was generated by pyright.
"""

from sys import version_info
from . import _deprecated_my_exceptions

_deprecated_names = [name for name in dir(_deprecated_my_exceptions) if not name.startswith("__")]
if version_info[: 2] >= (3, 7):
    def __getattr__(name):
        ...
    
else:
    ...
class WorkerInterrupt(Exception):
    """ An exception that is not KeyboardInterrupt to allow subprocesses
        to be interrupted.
    """
    ...


