"""
This type stub file was generated by pyright.
"""

import pickle

"""Utilities for fast persistence of big data, with optional compression."""
Unpickler = pickle._Unpickler
Pickler = pickle._Pickler
xrange = range
_IO_BUFFER_SIZE = 1024 ** 2
BUFFER_SIZE = 2 ** 18
