"""
This type stub file was generated by pyright.
"""

import pytest
import _pytest

"""
Helper for testing.
"""
raises = pytest.raises
warns = pytest.warns
SkipTest = _pytest.runner.Skipped
skipif = pytest.mark.skipif
fixture = pytest.fixture
parametrize = pytest.mark.parametrize
timeout = pytest.mark.timeout
xfail = pytest.mark.xfail
param = pytest.param
def warnings_to_stdout():
    """ Redirect all warnings to stdout.
    """
    ...

def check_subprocess_call(cmd, timeout=..., stdout_regex=..., stderr_regex=...):
    """Runs a command in a subprocess with timeout in seconds.

    Also checks returncode is zero, stdout if stdout_regex is set, and
    stderr if stderr_regex is set.
    """
    ...

