"""
This type stub file was generated by pyright.
"""

from celery.utils.imports import import_from_cwd, symbol_by_name

"""Get loader by name.

Loaders define how configuration is read, what happens
when workers start, when tasks are executed and so on.
"""
LOADER_ALIASES = { 'app': 'celery.loaders.app:AppLoader','default': 'celery.loaders.default:Loader' }
def get_loader_cls(loader):
    """Get loader class by name/alias."""
    ...

