"""
This type stub file was generated by pyright.
"""

def evaluate(code, path=..., mode=...):
    ...

class Observable(object):
    """An object with change notifications."""
    observers = ...
    def __init__(self) -> None:
        ...
    
    def __setattr__(self, name, value):
        ...
    


class Env(dict):
    """A dict for environment variables.
    """
    @staticmethod
    def snapshot():
        """Returns a snapshot of the current environment.
        """
        ...
    
    def copy(self, updated_from=...):
        ...
    
    def prepend_to(self, key, entry):
        """Prepends a new entry to a PATH-style environment variable, creating
        it if it doesn't exist already.
        """
        ...
    
    def for_popen(self):
        """Returns a copy of this dict, with all strings converted to the type
        suitable for subprocess.Popen() and other similar APIs.
        """
        ...
    


