"""
This type stub file was generated by pyright.
"""

from kombu.utils.imports import symbol_by_name

"""Pool implementation abstract factory, and alias definitions."""
ALIASES = { 'prefork': 'celery.concurrency.prefork:TaskPool','eventlet': 'celery.concurrency.eventlet:TaskPool','gevent': 'celery.concurrency.gevent:TaskPool','solo': 'celery.concurrency.solo:TaskPool','processes': 'celery.concurrency.prefork:TaskPool' }
def get_implementation(cls):
    """Return pool implementation by name."""
    ...

