"""
This type stub file was generated by pyright.
"""

"""Entry-point for the :program:`celery` umbrella command."""
def main():
    """Entrypoint to the ``celery`` umbrella command."""
    ...

if __name__ == '__main__':
    ...
