"""
This type stub file was generated by pyright.
"""

from kombu.utils.objects import cached_property
from kombu.utils.uuid import uuid
from .functional import chunks, memoize, noop
from .imports import gen_task_name, import_from_cwd, instantiate, qualname as get_full_cls_name, symbol_by_name as get_cls_by_name
from .log import LOG_LEVELS
from .nodenames import nodename, nodesplit, worker_direct

"""Utility functions.

Don't import from here directly anymore, as these are only
here for backwards compatibility.
"""
gen_unique_id = uuid
