"""
This type stub file was generated by pyright.
"""

"""Deprecation utilities."""
PENDING_DEPRECATION_FMT = """
    {description} is scheduled for deprecation in \
    version {deprecation} and removal in version v{removal}. \
    {alternative}
"""
DEPRECATION_FMT = """
    {description} is deprecated and scheduled for removal in
    version {removal}. {alternative}
"""
def warn(description=..., deprecation=..., removal=..., alternative=..., stacklevel=...):
    """Warn of (pending) deprecation."""
    ...

def Callable(deprecation=..., removal=..., alternative=..., description=...):
    """Decorator for deprecated functions.

    A deprecation warning will be emitted when the function is called.

    Arguments:
        deprecation (str): Version that marks first deprecation, if this
            argument isn't set a ``PendingDeprecationWarning`` will be
            emitted instead.
        removal (str): Future version when this feature will be removed.
        alternative (str): Instructions for an alternative solution (if any).
        description (str): Description of what's being deprecated.
    """
    ...

def Property(deprecation=..., removal=..., alternative=..., description=...):
    """Decorator for deprecated properties."""
    ...

class _deprecated_property:
    def __init__(self, fget=..., fset=..., fdel=..., doc=..., **depreinfo) -> None:
        ...
    
    def __get__(self, obj, type=...):
        ...
    
    def __set__(self, obj, value):
        ...
    
    def __delete__(self, obj):
        ...
    
    def setter(self, fset):
        ...
    
    def deleter(self, fdel):
        ...
    


