"""
This type stub file was generated by pyright.
"""

version_json = '''
{
 "date": "2020-09-30T11:56:03-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "49919cd40e6b99e100c08771f54df36f9338617c",
 "version": "1.0.0"
}
'''
def get_versions():
    ...

