"""
This type stub file was generated by pyright.
"""

from celery.utils.functional import firstmethod

"""Task Annotations.

Annotations is a nice term for monkey-patching task classes
in the configuration.

This prepares and performs the annotations in the
:setting:`task_annotations` setting.
"""
_first_match = firstmethod('annotate')
_first_match_any = firstmethod('annotate_any')
class MapAnnotation(dict):
    """Annotation map: task_name => attributes."""
    def annotate_any(self):
        ...
    
    def annotate(self, task):
        ...
    


def prepare(annotations):
    """Expand the :setting:`task_annotations` setting."""
    ...

def resolve_all(anno, task):
    """Resolve all pending annotations."""
    ...

