"""
This type stub file was generated by pyright.
"""

"""Backend selection."""
UNKNOWN_BACKEND = """
Unknown result backend: {0!r}.  Did you spell that correctly? ({1!r})
"""
BACKEND_ALIASES = { 'amqp': 'celery.backends.amqp:AMQPBackend','rpc': 'celery.backends.rpc.RPCBackend','cache': 'celery.backends.cache:CacheBackend','redis': 'celery.backends.redis:RedisBackend','rediss': 'celery.backends.redis:RedisBackend','sentinel': 'celery.backends.redis:SentinelBackend','mongodb': 'celery.backends.mongodb:MongoBackend','db': 'celery.backends.database:DatabaseBackend','database': 'celery.backends.database:DatabaseBackend','elasticsearch': 'celery.backends.elasticsearch:ElasticsearchBackend','cassandra': 'celery.backends.cassandra:CassandraBackend','couchbase': 'celery.backends.couchbase:CouchbaseBackend','couchdb': 'celery.backends.couchdb:CouchBackend','cosmosdbsql': 'celery.backends.cosmosdbsql:CosmosDBSQLBackend','riak': 'celery.backends.riak:RiakBackend','file': 'celery.backends.filesystem:FilesystemBackend','disabled': 'celery.backends.base:DisabledBackend','consul': 'celery.backends.consul:ConsulBackend','dynamodb': 'celery.backends.dynamodb:DynamoDBBackend','azureblockblob': 'celery.backends.azureblockblob:AzureBlockBlobBackend','arangodb': 'celery.backends.arangodb:ArangoDbBackend','s3': 'celery.backends.s3:S3Backend' }
def by_name(backend=..., loader=..., extension_namespace=...):
    """Get backend class by name/alias."""
    ...

def by_url(backend=..., loader=...):
    """Get backend class by URL."""
    ...

