"""
This type stub file was generated by pyright.
"""

import sys
import threading

_tls = threading.local()
_config = { "qt": "auto","subProcess": True,"python": sys.executable }
_config_valid_values = { "qt": ["auto", "none", "pyside", "pyside2", "pyqt4", "pyqt5"] }
_adapter_process = None
def ensure_logging():
    """Starts logging to log.log_dir, if it hasn't already been done.
    """
    ...

def log_to(path):
    ...

def configure(properties, **kwargs):
    ...

@_starts_debugging
def listen(address, settrace_kwargs):
    ...

@_starts_debugging
def connect(address, settrace_kwargs, access_token):
    ...

def wait_for_client():
    ...

def is_client_connected():
    ...

def breakpoint():
    ...

def debug_this_thread():
    ...

def trace_this_thread(should_trace):
    ...

