"""
This type stub file was generated by pyright.
"""

from celery.utils.functional import LRUCache

"""Utility to dump events to screen.

This is a simple program that dumps events to the console
as they happen.  Think of it like a `tcpdump` for Celery events.
"""
TASK_NAMES = LRUCache(limit=4095)
HUMAN_TYPES = { 'worker-offline': 'shutdown','worker-online': 'started','worker-heartbeat': 'heartbeat' }
CONNECTION_ERROR = """\
-> Cannot connect to %s: %s.
Trying again %s
"""
def humanize_type(type):
    ...

class Dumper:
    """Monitor events."""
    def __init__(self, out=...) -> None:
        ...
    
    def say(self, msg):
        ...
    
    def on_event(self, ev):
        ...
    
    def format_task_event(self, hostname, timestamp, type, task, event):
        ...
    


def evdump(app=..., out=...):
    """Start event dump."""
    ...

if __name__ == '__main__':
    ...
